import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hardhat React Hooks Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Hardhat React Hooks Usage</h1>

          <h3>Read</h3>
          <pre>
            <code>
              {`import useContractMethod from './hooks'`}<br /><br />
              {`const { read, loading, error } = useContractMethod()`}<br /><br />
              {`async function() {`}<br />
              &emsp;{`  if (await read()) {`}<br />
              &emsp;&emsp;{`    // success`}<br />
              &emsp;{`  }`}<br />
              {`}`}<br />
            </code>
          </pre>

          <h3>Write</h3>
          <pre>
            <code>
              {`import useContractMethod from './hooks'`}<br /><br />
              {`const { write, processing, error, tx, receipt } = useContractMethod()`}<br /><br />
              {`async function() {`}<br />
              &emsp;{`if (await write(params)) {`}<br />
              &emsp;&emsp;{`// success`}<br />
              &emsp;{`}`}<br />
              {`}`}<br /><br />
              {`useEffect(() => {`}<br />
              &emsp;{`//receipt data...`}<br />
              {`}, [receipt])`}<br />
            </code>
          </pre>

          <h3>Events</h3>
          <pre>
            <code>
              {`import useContractEvent from './hooks'`}<br /><br />
              {`const { listenToEvent, eventData, eventError } = useContractEvent()`}<br /><br />
              {`useEffect(() => {`}<br />
              &emsp;{`listenToEvent()`}<br />
              {`})`}<br /><br />
              {`useEffect(() => {`}<br />
              &emsp;{`//event data...`}<br />
              {`}, [eventData])`}<br /><br />
              {`useEffect(() => {`}<br />
              &emsp;{`//event error`}<br />
              {`}, [eventError])`}<br />
            </code>
          </pre>
        </div>
      </main>
    </>
  )
}
